#!/usr/bin/env python3
"""Plot SmokeLens training loss and accuracy from training_history.csv."""

from __future__ import annotations

import argparse
import csv
import os
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--history",
        default=REPO_ROOT / "ml" / "results" / "training_history.csv",
        type=Path,
        help="Training history CSV generated by train.py.",
    )
    parser.add_argument(
        "--out-dir",
        default=REPO_ROOT / "ml" / "results",
        type=Path,
        help="Directory for generated PNG files.",
    )
    return parser.parse_args()


def optional_float(value: str | None) -> float | None:
    if value is None or not value.strip():
        return None
    return float(value)


def load_history(path: Path) -> dict[str, list[float | None]]:
    if not path.exists():
        raise FileNotFoundError(f"Training history not found: {path}")

    columns = {
        "epoch": [],
        "train_loss": [],
        "train_accuracy": [],
        "validation_loss": [],
        "validation_accuracy": [],
    }
    with path.open(newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        missing = set(columns) - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing history columns: {', '.join(sorted(missing))}")
        for row in reader:
            columns["epoch"].append(float(row["epoch"]))
            for name in columns.keys() - {"epoch"}:
                columns[name].append(optional_float(row[name]))

    if not columns["epoch"]:
        raise ValueError(f"Training history is empty: {path}")
    return columns


def valid_series(
    epochs: list[float | None], values: list[float | None]
) -> tuple[list[float], list[float]]:
    pairs = [
        (float(epoch), float(value))
        for epoch, value in zip(epochs, values)
        if epoch is not None and value is not None
    ]
    return [pair[0] for pair in pairs], [pair[1] for pair in pairs]


def save_plot(plt, history, train_column, validation_column, ylabel, path):
    plt.figure(figsize=(9, 5))
    train_epochs, train_values = valid_series(history["epoch"], history[train_column])
    plt.plot(train_epochs, train_values, label="training", linewidth=2)

    validation_epochs, validation_values = valid_series(
        history["epoch"], history[validation_column]
    )
    if validation_values:
        plt.plot(validation_epochs, validation_values, label="validation", linewidth=2)

    plt.xlabel("Epoch")
    plt.ylabel(ylabel)
    plt.title(f"Training and Validation {ylabel}")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(path, dpi=160)
    plt.close()


def main() -> None:
    args = parse_args()
    cache_dir = Path(tempfile.gettempdir()) / "smokelens-matplotlib"
    cache_dir.mkdir(parents=True, exist_ok=True)
    os.environ.setdefault("MPLCONFIGDIR", str(cache_dir))
    os.environ.setdefault("XDG_CACHE_HOME", str(cache_dir))
    try:
        import matplotlib.pyplot as plt
    except ModuleNotFoundError as error:
        raise SystemExit(
            "Missing matplotlib. Install with: "
            "python3 -m pip install -r ml/requirements-ml.txt"
        ) from error

    history = load_history(args.history)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    loss_path = args.out_dir / "loss_curve.png"
    accuracy_path = args.out_dir / "accuracy_curve.png"
    save_plot(
        plt,
        history,
        "train_loss",
        "validation_loss",
        "Loss",
        loss_path,
    )
    save_plot(
        plt,
        history,
        "train_accuracy",
        "validation_accuracy",
        "Accuracy",
        accuracy_path,
    )
    print(f"Wrote {loss_path}")
    print(f"Wrote {accuracy_path}")


if __name__ == "__main__":
    main()
